# Generated by Django 4.2 on 2023-05-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='color_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='update_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
