# Generated by Django 4.2 on 2023-05-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categories_color_id_categories_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='category',
            new_name='category_id',
        ),
    ]
