# Generated by Django 4.2 on 2024-01-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_myuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='CustomUser',
        ),
    ]
