# Generated by Django 4.2 on 2023-06-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_category_notes_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='category_id',
            new_name='category',
        ),
    ]
