# Generated by Django 4.2 on 2024-01-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_myuser_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
